### ISSUE TITLE
Inferenece Demo?

### ISSUE THREAD

**Issue by dragen1860** [kakaobrain/bassl#1]
Dear author:
   Thanks for contributing an insightful work and make it published! it's helpful!
   Your readme instruction file is really detailed. However, I can not find a "inference demo on single video" script . For a lot of researchers, A simple demo code will be the first step to try and play with your work. Thank you.

**Comment by JonghwanMun** [comment]
Unfortunately the current version only supports training and evaluation of our model.
We cannot give an exact date, but we plan to release an inference demo as soon as possible.

**Comment by baigang666** [comment]
> Unfortunately the current version only supports training and evaluation of our model. We cannot give an exact date, but we plan to release an inference demo as soon as possible.

when release inference demo?   thank you
