### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 19268587 (char 19268586)

### ISSUE THREAD

**Issue by Bo396543018** [kakaobrain/bassl#11]
When I ran the pretrain code，loading anno.pretrain.ndjson raised this problem ‘json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 19268587 (char 19268586)’. Is there a  format issue in the anno.pretrain.ndjson？

**Comment by JonghwanMun** [comment]
Can you check that the downloaded data is not broken?

**Comment by Bo396543018** [comment]
Thanks for your replay, I fixed this problem by generating a new file with same content.

> Can you check that the downloaded data is not broken?
