### ISSUE TITLE
What is the hardware spec for fine-tuning the model?

### ISSUE THREAD

**Issue by riven314** [kakaobrain/bassl#3]
e.g.
What is the minimum GPU memory required for fine-tuning?
How long did it take to do fine-tuning?

**Comment by JonghwanMun** [comment]
For 1 V100 GPU, it takes < 2 hours for the shot-level feature extraction and < half day for fine-tuning using the extracted shot-level features.

When we pre-extract shot-level features and use them for fine-tuning, less than 2GB GPU memory is required; thus most types of GPU can be used for fine-tuning.

**Comment by riven314** [comment]
thanks for the address!
