### ISSUE TITLE
Hardcode path in MovieNetMetric() init

### ISSUE THREAD

**Issue by Bonnie970** [kakaobrain/bassl#4]
Thanks for open sourcing your great work.

 Found two hardcoded paths in bassl/finetune/utils/metric.py line181 and 186, causing not found error when this method is being called.  Also, vid2ind.json and shot files are not included in anno.tar.

**Comment by JonghwanMun** [comment]
Now, I fix it. Thank you for sharing such hardcoded path for loading data.
However, to run the evaluation, you need to download annotation files from [MovieNet-SSeg google drive](https://drive.google.com/drive/folders/1F-uqCKnhtSdQKcDUiL3dRcLOrAxHargz) and put the folder `scene318` into `<path-to-root>/bassl/data/movienet`.
