### ISSUE TITLE
MovieNet-SSeg data

### ISSUE THREAD

**Issue by Dobby114** [kakaobrain/bassl#6]
Thank you very much for your generous sharing, but I ran into some problems with the implementation.
During the data preparation stage, I tried to download the data with the command `bash scripts/download_movienet_data.sh`
but I failed, and got the following prompt：
![Snipaste_2022-07-14_13-29-55](https://user-images.githubusercontent.com/66785750/178906672-60a60ee3-596b-466f-92b9-65a657090184.png)
How can I get the key-frames of MovieNet-SSeg dataset?

**Comment by JonghwanMun** [comment]
It seems that the official provider of MovieNet changes the policy to download data as follows:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/6416693/179644298-c9045c52-98a8-4a65-a3ad-e2b0135b5036.png">

Thus, I think you can download key-frames by moving to [OpenDataLab](https://opendatalab.com/MovieNet/download), registering an account and logging in to download data.

**Comment by Dobby114** [comment]
> 看来MovieNet的官方提供者将下载数据的政策更改如下：
> 
> <img alt="图片" width="800" src="https://user-images.githubusercontent.com/6416693/179644298-c9045c52-98a8-4a65-a3ad-e2b0135b5036.png">
> 
> 因此，我认为您可以通过转到[OpenDataLab](https://opendatalab.com/MovieNet/download)、注册帐户并登录以下载数据来下载关键帧。
Thank you very much for your patient reply！

**Comment by Dobby114** [comment]
> It seems that the official provider of MovieNet changes the policy to download data as follows:
> 
> <img alt="image" width="800" src="https://user-images.githubusercontent.com/6416693/179644298-c9045c52-98a8-4a65-a3ad-e2b0135b5036.png">
> 
> Thus, I think you can download key-frames by moving to [OpenDataLab](https://opendatalab.com/MovieNet/download), registering an account and logging in to download data.

Thank you very much for your patient reply！
