### ISSUE TITLE
Missing vid2idx.json 

### ISSUE THREAD

**Issue by pida0** [kakaobrain/bassl#7]
Many thanks for sharing your code.

I download anno.tar from https://arena.kakaocdn.net/brainrepo/bassl/data/anno.tar, and I can't find vid2idx.json, where can I get this file?

**Comment by JonghwanMun** [comment]
[vid2idx.json](https://github.com/kakaobrain/bassl/blob/551fe94343debf60a64c787be6752284153a0f7a/bassl/data/movienet/anno/vid2idx.json) is self-contained in this repository.
There is no need to download it using an external link.

**Comment by pida0** [comment]
> [vid2idx.json](https://github.com/kakaobrain/bassl/blob/551fe94343debf60a64c787be6752284153a0f7a/bassl/data/movienet/anno/vid2idx.json) is self-contained in this repository. There is no need to download it using an external link.


Thanks for your quick reply😀, I'v found this file
